version: "3.3"
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'validationbilel'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
  backend:
    depends_on:
      - mysqldb
    image: validationbackend:1.0
    ports:
      - "8089:8089"
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/db?useSSL=false
      spring.datasource.username: 'user'
      spring.datasource.password: 'password'

  # Frontend Service 
  frontend:
    image: front4
    ports:
      - "8090:80" # Map the exposed port 80 on the container to port 8081 on the host machine
    restart: always
    depends_on:
      - backend  

